### ISSUE TITLE
Better Structure in General section

### ISSUE THREAD

**Issue by ssarmokadam** [devonfw/devon4j#450] opened 2021-08-26 06:27 UTC
we have multiple articles in a general section. we need to define proper structure for it like adding subsection guides as we have it here https://devonfw.com/website/pages/docs/devon4j.wiki_devon4j.asciidoc_guides.html

**Comment by hohwille** [comment] 2022-06-30 16:54
I consider this issue as a duplicate of #511 and will also close it.

**Closed as completed by hohwille** 2022-06-30 16:54 UTC
Labels: enhancement, documentation
